/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inventorymanagementsystemv_01;
//import inventorymanagementSystemv_01.
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import custom_ui.CustomTitleBar;
import custom_ui.RoundedPanel;
/**
 *
 * @author Ugochukwu Nwodo
 */
public class TestingUI extends javax.swing.JFrame {
    private CustomTitleBar titleBar;
    /**
     * Creates new form TestingUI
     */
    public TestingUI() {
       setUndecorated(true);
       initComponents();

       // Create a wrapper with BorderLayout
       javax.swing.JPanel wrapper = new javax.swing.JPanel(new java.awt.BorderLayout());

       // Title bar at top
       titleBar = new CustomTitleBar(this);
       titleBar.setBarColor(new java.awt.Color(45, 55, 98));
       titleBar.setTitleText("Inventory Management System");

       // roundedPanel4 is your main content panel from the designer
       wrapper.add(titleBar, java.awt.BorderLayout.NORTH);
       wrapper.add(roundedPanel4, java.awt.BorderLayout.CENTER);

       setContentPane(wrapper);
       setSize(900, 600);
       setLocationRelativeTo(null);
       JPanel starters = new JPanel(new FlowLayout());
        starters.add(new JLabel("starters..."));
        JPanel drinks = new JPanel(new FlowLayout());
        drinks.add(new JLabel("drinks..."));
        drinks.add(new JLabel("Coke..."));
        drinks.add(new JLabel("drinks..."));

        JPanel main = new JPanel(new CardLayout());
        main.add(starters, "starters");
        main.add(drinks, "drinks");

        JPanel buttons = new JPanel();
        JButton startersButton = new JButton("Starters");
        startersButton.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                CardLayout cl = (CardLayout)(main.getLayout());
                cl.show(main, "starters");
            }
        });

        JButton drinksButton = new JButton("Drinks");
        drinksButton.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                CardLayout cl = (CardLayout)(main.getLayout());
                cl.show(main, "drinks");
            }
        });

        buttons.add(startersButton);
        buttons.add(drinksButton);

        setLayout(new BorderLayout());
        add(main);
        add(buttons, BorderLayout.PAGE_START);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel4 = new custom_ui.RoundedPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1300, 580));

        roundedPanel4.setBackground(new java.awt.Color(153, 204, 255));
        roundedPanel4.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout roundedPanel4Layout = new javax.swing.GroupLayout(roundedPanel4);
        roundedPanel4.setLayout(roundedPanel4Layout);
        roundedPanel4Layout.setHorizontalGroup(
            roundedPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1352, Short.MAX_VALUE)
        );
        roundedPanel4Layout.setVerticalGroup(
            roundedPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 523, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(roundedPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(roundedPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestingUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestingUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private custom_ui.RoundedPanel roundedPanel4;
    // End of variables declaration//GEN-END:variables
}
